package gui;

import de.fk.neuralnetwork.Main;
import de.fk.neuralnetwork.NeuralNetwork;
import de.fk.neuralnetwork.data.ImageContainer;
import de.fk.neuralnetwork.learning.Backpropagator;
import de.fk.neuralnetwork.training.LabeledImageTrainingSupplier;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Felix
 */
public class MainFrame extends javax.swing.JFrame {

    private TrainingExamplesFrame teframe = null;
    private DrawFrame dframe = null;
    private NeuralNetwork nn;
    private Backpropagator bp = null;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        //nn = new NeuralNetwork(1, 300, 28*28, 10);
        nn = new NeuralNetwork(28 * 28, 10, new int[]{300, 100});
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        btnTrain = new javax.swing.JButton();
        btnStopTraining = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mbNetwork = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        mbTraining = new javax.swing.JMenu();
        miTrainingExamples = new javax.swing.JMenuItem();
        mbTest = new javax.swing.JMenu();
        mbTestMNIST = new javax.swing.JMenuItem();
        mbTestDraw = new javax.swing.JMenuItem();

        fileChooser.setCurrentDirectory(new java.io.File("D:\\Dokumente\\NetBeansProjects\\BeLL_NeuralNetwork"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Neuronales Netz zur Handschrifterkennung");

        btnTrain.setText("Training beginnen");
        btnTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainActionPerformed(evt);
            }
        });

        btnStopTraining.setText("Training stoppen");
        btnStopTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopTrainingActionPerformed(evt);
            }
        });

        mbNetwork.setText("Netz");

        miOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOpen.setText("Öffnen");
        miOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenActionPerformed(evt);
            }
        });
        mbNetwork.add(miOpen);

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSave.setText("Speichern");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        mbNetwork.add(miSave);

        menuBar.add(mbNetwork);

        mbTraining.setText("Trainieren");

        miTrainingExamples.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        miTrainingExamples.setText("Trainingsbeispiele");
        miTrainingExamples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTrainingExamplesActionPerformed(evt);
            }
        });
        mbTraining.add(miTrainingExamples);

        menuBar.add(mbTraining);

        mbTest.setText("Testen");

        mbTestMNIST.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mbTestMNIST.setText("Mit MNIST testen");
        mbTestMNIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbTestMNISTActionPerformed(evt);
            }
        });
        mbTest.add(mbTestMNIST);

        mbTestDraw.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mbTestDraw.setText("Zeichenfeld");
        mbTestDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbTestDrawActionPerformed(evt);
            }
        });
        mbTest.add(mbTestDraw);

        menuBar.add(mbTest);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnStopTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStopTraining)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miTrainingExamplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTrainingExamplesActionPerformed
        if(teframe == null || !teframe.isDisplayable()) teframe = new TrainingExamplesFrame();
        teframe.setVisible(true);
    }//GEN-LAST:event_miTrainingExamplesActionPerformed

    private void btnTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainActionPerformed
        LabeledImageTrainingSupplier trainingSupplier = new LabeledImageTrainingSupplier(ImageContainer.getImages(), 28, 28, 10);
        
        bp = new Backpropagator(nn, 0.005, 0);
        FileOutputStream fos = null;
        try {
            //Logging
            fos = new FileOutputStream("errorlog.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        bp.train(trainingSupplier, 500, fos, 1);
    }//GEN-LAST:event_btnTrainActionPerformed

    private void btnStopTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTrainingActionPerformed
        if(bp != null) bp.stopTraining();
    }//GEN-LAST:event_btnStopTrainingActionPerformed

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        if(fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                nn.sout();
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileChooser.getSelectedFile()));
                oos.writeObject(nn);
                oos.close();
            } catch (IOException | NullPointerException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miSaveActionPerformed

    private void miOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenActionPerformed
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileChooser.getSelectedFile()));
                nn = (NeuralNetwork) ois.readObject();
                ois.close();
            } catch (IOException | NullPointerException | ClassNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOpenActionPerformed

    private void mbTestMNISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbTestMNISTActionPerformed
        new MnistTestDialog(this, true, nn).setVisible(true);
    }//GEN-LAST:event_mbTestMNISTActionPerformed

    private void mbTestDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbTestDrawActionPerformed
        if(dframe == null || !dframe.isDisplayable()) dframe = new DrawFrame(nn);
        dframe.setVisible(true);
    }//GEN-LAST:event_mbTestDrawActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStopTraining;
    private javax.swing.JButton btnTrain;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu mbNetwork;
    private javax.swing.JMenu mbTest;
    private javax.swing.JMenuItem mbTestDraw;
    private javax.swing.JMenuItem mbTestMNIST;
    private javax.swing.JMenu mbTraining;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JMenuItem miTrainingExamples;
    // End of variables declaration//GEN-END:variables
}
