package gui;

import de.fk.neuralnetwork.data.ImageContainer;
import de.fk.neuralnetwork.data.LabeledImage;
import de.fk.neuralnetwork.data.Tester;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Felix
 */
public class TrainingExamplesFrame extends javax.swing.JFrame {

    private MainFrame mfr;
    
    /**
     * Creates new form TrainingExamplesFrame
     * @param mfr
     */
    public TrainingExamplesFrame(MainFrame mfr) {
        this.mfr = mfr;
        initComponents();
    }
    
    public TrainingExampleDisplayPanel getDisplayPanel() {
        return (TrainingExampleDisplayPanel) displayPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        lblState = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        tfPosition = new javax.swing.JTextField();
        btnForward = new javax.swing.JButton();
        displayPanel = new TrainingExampleDisplayPanel(ImageContainer.getImages());
        menuBar = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        miImportMnist = new javax.swing.JMenuItem();
        miReset = new javax.swing.JMenuItem();
        miClose = new javax.swing.JMenuItem();
        mnView = new javax.swing.JMenu();
        miShowAll = new javax.swing.JMenuItem();
        miShowIncorrect = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trainingsbeispiele");

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        lblState.setText("    0 Trainingsbeispiele geladen.    ");
        toolBar.add(lblState);

        btnBack.setText("<");
        btnBack.setFocusable(false);
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnBack);

        tfPosition.setText("0");
        tfPosition.setMaximumSize(new java.awt.Dimension(50, 2147483647));
        toolBar.add(tfPosition);

        btnForward.setText(">");
        btnForward.setFocusable(false);
        btnForward.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnForward.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnForward);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        mnFile.setText("Datei");

        miImportMnist.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miImportMnist.setText("Aus MNIST importieren");
        miImportMnist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportMnistActionPerformed(evt);
            }
        });
        mnFile.add(miImportMnist);

        miReset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        miReset.setText("Trainingsbeispiele zurücksetzen");
        miReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miResetActionPerformed(evt);
            }
        });
        mnFile.add(miReset);

        miClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        miClose.setText("Schließen");
        miClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCloseActionPerformed(evt);
            }
        });
        mnFile.add(miClose);

        menuBar.add(mnFile);

        mnView.setText("Ansicht");

        miShowAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        miShowAll.setText("Alle anzeigen");
        miShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miShowAllActionPerformed(evt);
            }
        });
        mnView.add(miShowAll);

        miShowIncorrect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        miShowIncorrect.setText("Falsch Klassifizierte anzeigen");
        miShowIncorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miShowIncorrectActionPerformed(evt);
            }
        });
        mnView.add(miShowIncorrect);

        menuBar.add(mnView);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateImages() {
        lblState.setText("    " + getDisplayPanel().getImageList().size() + " Trainingsbeispiele geladen.    ");
        displayPanel.repaint();
    }
    
    private void miImportMnistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportMnistActionPerformed
        new MnistImportDialog(this, true).setVisible(true);
        updateImages();
    }//GEN-LAST:event_miImportMnistActionPerformed

    private void miResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miResetActionPerformed
        ImageContainer.clear();
        updateImages();
    }//GEN-LAST:event_miResetActionPerformed

    private void miCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCloseActionPerformed
        dispose();
    }//GEN-LAST:event_miCloseActionPerformed

    private void miShowIncorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miShowIncorrectActionPerformed
        HashMap<LabeledImage, Double> imgs = Tester.findIncorrectlyClassified(mfr.getNet(), ImageContainer.getImages());
        getDisplayPanel().setImageList(new ArrayList<>(imgs.keySet()));
        updateImages();
    }//GEN-LAST:event_miShowIncorrectActionPerformed

    private void miShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miShowAllActionPerformed
        getDisplayPanel().setImageList(ImageContainer.getImages());
        updateImages();
    }//GEN-LAST:event_miShowAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnForward;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel lblState;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miClose;
    private javax.swing.JMenuItem miImportMnist;
    private javax.swing.JMenuItem miReset;
    private javax.swing.JMenuItem miShowAll;
    private javax.swing.JMenuItem miShowIncorrect;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnView;
    private javax.swing.JTextField tfPosition;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
